/*
 * r2ai -e api=groq
 * r2ai -e model=llama-3.3-70b-versatile
 * r2ai -e lang=rust
 * r2ai -d
 * This is the code generated by the AI for sym.dockcode::main::h786b1da3968f45ab at 0x00009b90
 * NB. This source code is correct for the global idea, but quite incorrect in the details!
 */

fn dockcode_main(input1: i64, input2: i64) -> i64 {
    let authorization_code = "EpdlsPjpo:".to_string();
    let mut user_input = String::new();

    println!("Enter docking authorization code: ");

    std::io::stdin().read_line(&mut user_input).expect("Failed to read line");

    let trimmed_input = user_input.trim();

    if trimmed_input == authorization_code {
        println!("Docking sequence authorized. We are cleared to dock.");
    } else {
        println!("Authorization failed. Access denied.\nDocking sequence authorization failed.");
    }

    return 1;
}
